name: Run tests

on:
  push:
    branches-ignore:
      - future
  pull_request:
    branches-ignore:
      - future


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: |
        chmod +x ./test.sh
        ./test.sh
